@@ -0,0 +1,25 @@
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      role: backend
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
      - name: backend
        image: blocnotas/backend
        ports:
        - containerPort: 3800
        
        
        
        
        @@ -0,0 +1,13 @@
apiVersion: v1
kind: Service
metadata:
  name: backend-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3800
      name: http
  selector:
    role: backend
